# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('key', models.TextField()),
                ('finger_print', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('uid', models.IntegerField()),
                ('gecos', models.CharField(max_length=128)),
                ('shell', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('directory', models.CharField(max_length=256)),
                ('expiry_date', models.DateField()),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='server',
            field=models.ManyToManyField(to='stns.Server'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(to='stns.User'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.User'),
        ),
    ]
