# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('key', models.TextField()),
                ('finger_print', models.CharField(blank=True, editable=False, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Role')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Server')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('uid', models.IntegerField(unique=True)),
                ('gecos', models.CharField(blank=True, max_length=128)),
                ('shell', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('directory', models.CharField(blank=True, max_length=256)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('disabled', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='stns.UserRoleMembership', to='stns.Role'),
        ),
        migrations.AddField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(through='stns.ServerRoleMembership', to='stns.Role'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.User'),
        ),
    ]
