# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
