# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stns', '0003_auto_20171027_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
