# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stns', '0004_auto_20171027_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='finger_print',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='server',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
