# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stns', '0005_auto_20171027_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='publickey',
            name='finger_print',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
