# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stns', '0006_auto_20171028_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='server',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='userrolemembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Role'),
        ),
        migrations.AddField(
            model_name='userrolemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.User'),
        ),
        migrations.AddField(
            model_name='serverrolemembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Role'),
        ),
        migrations.AddField(
            model_name='serverrolemembership',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stns.Server'),
        ),
    ]
